slack:
  webhook-url: https://hooks.slack.com/services/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

---

crawling:
  ddc-url: https://www.ddc.go.kr/ddc/selectGosiList.do?key=469&not_ancmt_se_code=05

